name: Deploy a Surge.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar Surge.sh
        run: npm install -g surge

      - name: Desplegar a Surge.sh
        run: surge ./ --domain https://yelisweb.surge.sh --token ${{ secrets.SURGE_TOKEN }}
